### ISSUE TITLE
Error on C99

### ISSUE THREAD

**Issue by hw762** [SanderMertens/flecs#892]
**Describe the bug**
Trying to compile on an Ubuntu 22.04 machine, getting compiler error.

**To Reproduce**
Try to compile with `-std=c99`. Fail with following error:

```
src/flecs.c: In function ‘posix_time_setup’:
src/flecs.c:19462:9: warning: implicit declaration of function ‘clock_gettime’ [-Wimplicit-function-declaration]
19462 |         clock_gettime(CLOCK_MONOTONIC, &ts);
      |         ^~~~~~~~~~~~~
src/flecs.c:19462:23: error: ‘CLOCK_MONOTONIC’ undeclared (first use in this function)
19462 |         clock_gettime(CLOCK_MONOTONIC, &ts);
      |                       ^~~~~~~~~~~~~~~
src/flecs.c:19462:23: note: each undeclared identifier is reported only once for each function it appears in
src/flecs.c: In function ‘posix_sleep’:
src/flecs.c:19478:9: warning: implicit declaration of function ‘nanosleep’ [-Wimplicit-function-declaration]
19478 |     if (nanosleep(&sleepTime, NULL)) {
      |         ^~~~~~~~~
src/flecs.c: In function ‘posix_time_now’:
src/flecs.c:19510:23: error: ‘CLOCK_MONOTONIC’ undeclared (first use in this function)
19510 |         clock_gettime(CLOCK_MONOTONIC, &ts);
      |                       ^~~~~~~~~~~~~~~
src/flecs.c: In function ‘http_getnameinfo’:
src/flecs.c:37213:12: warning: implicit declaration of function ‘getnameinfo’; did you mean ‘http_getnameinfo’? [-Wimplicit-function-declaration]
37213 |     return getnameinfo(addr, (uint32_t)addr_len, host, (uint32_t)host_len,
      |            ^~~~~~~~~~~
      |            http_getnameinfo
src/flecs.c: In function ‘http_init_connection’:
src/flecs.c:37853:13: error: ‘NI_NUMERICHOST’ undeclared (first use in this function)
37853 |             NI_NUMERICHOST | NI_NUMERICSERV))
      |             ^~~~~~~~~~~~~~
src/flecs.c:37853:30: error: ‘NI_NUMERICSERV’ undeclared (first use in this function)
37853 |             NI_NUMERICHOST | NI_NUMERICSERV))
      |                              ^~~~~~~~~~~~~~
src/flecs.c: In function ‘http_accept_connections’:
src/flecs.c:37899:32: error: ‘NI_NUMERICHOST’ undeclared (first use in this function)
37899 |         ECS_SIZEOF(addr_port), NI_NUMERICHOST | NI_NUMERICSERV))
      |                                ^~~~~~~~~~~~~~
src/flecs.c:37899:49: error: ‘NI_NUMERICSERV’ undeclared (first use in this function)
37899 |         ECS_SIZEOF(addr_port), NI_NUMERICHOST | NI_NUMERICSERV))
```

Recompile with `-std=gnu99`, and error is gone.

**Expected behavior**
Compile success

**Comment by SanderMertens** [comment]
Unfortunately those constants aren't provided by C99 but they are necessary when using features of Flecs that require measuring time (like running at a target FPS, measuring system time etc).

You can also get rid of the errors by specifying `-D_XOPEN_SOURCE=600`

**Comment by SanderMertens** [comment]
I added a note to the README on how to fix the compiler errors.
