### ISSUE TITLE
When trying to build with bake in macOS Catalina 10.15.1, uint is not defined

### ISSUE THREAD

**Issue by WEREMSOFT** [SanderMertens/flecs#108]
**Describe the bug**
Bake command fails on MacOS

Seems to be related with this bug(should fix it) https://github.com/flecs-hub/flecs-systems-admin/issues/3

**To Reproduce**
1. Run `bake clone SanderMertens/flecs`
2. Run `cd flecs`
3. Run `bake`
4. The following error appears:

```
[  build] template flecs => 'templates/flecs'
[  build] template flecs.graphics => 'templates/flecs-graphics'
[  build] template flecs.module => 'templates/flecs-module'
Pablos-MacBook-Pro-2:flecs pabloweremczuk$ bake clean
[  clean] package flecs => '.'
[  clean] template flecs => 'templates/flecs'
[  clean] template flecs.graphics => 'templates/flecs-graphics'
[  clean] template flecs.module => 'templates/flecs-module'
Pablos-MacBook-Pro-2:flecs pabloweremczuk$ bake
[  build] package flecs => '.'
[     6%] worker.c
[    12%] table.c
[    18%] entity.c
[    25%] stage.c
[    31%] vector.c
[    37%] system.c
[    43%] world.c
[    50%] stats.c
[    56%] chunked.c
[    62%] err.c
./src/err.c:131:9: error: expected ';' after expression
    uint position = 0;
        ^
        ;
./src/err.c:131:5: error: use of undeclared identifier 'uint'; did you mean 'rint'?
    uint position = 0;
    ^~~~
    rint
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/math.h:468:15: note: 'rint' declared here
extern double rint(double);
              ^
./src/err.c:131:10: error: use of undeclared identifier 'position'
    uint position = 0;
         ^
./src/err.c:136:13: error: use of undeclared identifier 'position'
            position = strlen(signature) - 1;
            ^
./src/err.c:139:13: error: use of undeclared identifier 'position'
            position = pointer_to_string - signature;
            ^
./src/err.c:147:15: error: use of undeclared identifier 'position'
    for(; i < position; i++){
              ^
./src/err.c:131:5: warning: expression result unused [-Wunused-value]
    uint position = 0;
    ^~~~
1 warning and 6 errors generated.
error process 44242 exited with returncode 1
 from command returned 1
   clang -fPIC -fno-stack-protector -g -O0 -std=c99 -D_XOPEN_SOURCE=600 -Wall -D__BAKE__ -D__BAKE__ -DBAKE_PROJECT_ID="flecs" -DFLECS_IMPL -include ./.bake_cache/x64-Darwin-debug/include/flecs.h -I./include -I /Users/pabloweremczuk/bake/include -c ./src/err.c -o .bake_cache/x64-Darwin-debug/obj/err.o
 from command for task 'err.c' failed
 from dependency 'objects' failed
 from failed to build rule 'ARTEFACT'
[  error] build interrupted for flecs in .
error project 'flecs' built with errors, skipping
error project dependency graph contains cycles (1 built vs 4 total)
```

**Expected behavior**
The following output is expected for the command `bake`

```
[  build] package flecs => '.'
[    62%] err.c
[    68%] type.c
[    75%] os_api.c
[    81%] map.c
[    87%] misc.c
[    93%] parser.c
[   100%] column_system.c
[  build] template flecs => 'templates/flecs'
[  build] template flecs.graphics => 'templates/flecs-graphics'
[  build] template flecs.module => 'templates/flecs-module'
```

**Additional context**
This is `gcc -v output`
```
Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: x86_64-apple-darwin19.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
Running on MacOS Catalina 10.15.1

**Comment by WEREMSOFT** [comment]
I don't know why but the bug is not present anymore. I cleaned and deleted generated folders and now is working.

**Comment by SanderMertens** [comment]
Great, thanks for letting me know!
